#!/bin/sh
set -x

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  mkdir /etc/dropbear
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

# exec runsv /opt/service/dropbear | sed 's/^/dropbear: /'


# udevd -daemon
# mount -t devtmpfs udev /dev/
modprobe bcm2835_v4l2
chmod 666 /dev/video0
